[package]
name = "n"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.45", features = ["derive"] }
rusqlite = { version = "0.37.0", features = ["bundled"] }
shellexpand = "3.1.1"
tempfile = "3.21.0"
uuid = { version = "1.18.0", features = ["v4"] }
